version: '3.2'
services:
  erlang-in-anger-pdf-compile:
    image: ghcr.io/ymotongpoo/erlang-in-anger-pdf:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      cache_from:
        - ghcr.io/ymotongpoo/erlang-in-anger-pdf:latest
    volumes:
      - .:/workdir
